version: 2
jobs:
  build:
    docker:
      - image: rocker/verse
    environment:
      R_LIBS: ~/R/Library
    steps:
      - restore_cache:
          keys:
            - r-pkg-cache-{{ arch }}-{{ .Branch }}
            - r-pkg-cache-{{ arch }}-
      - checkout
      - run:
          name: Install package dependencies
          command: |
            export DEBIAN_FRONTEND=noninteractive; apt-get -y update && apt-get install -y git-core
            mkdir -p ~/R/Library
            Rscript -e 'install.packages(c("remotes", "devtools"))'
            install2.r dplyr forcats ggplot2 glue googlesheets4 here purrr readr remotes shiny stringr tibble tidyr tidyverse todor gargle
            Rscript -e 'devtools::install_github("ropensci/rcrossref@319f34c8e8cbb41c2cb06282e612b870f61b85cd")'
            #installGithub.r ropensci/rcrossref@319f34c8e8cbb41c2cb06282e612b870f61b85cd
      - run:
          name: Run prep
          command: |
            Rscript -e 'rcrossref::cr_cn("10.3389/fninf.2021.678403")'
            Rscript -e 'googlesheets4::gs4_auth("teetaps111@gmail.com")'
            
            echo RUNNING PREP SCRIPTS
      - run:
          name: Session information and installed package versions
          command: |
            Rscript -e 'sessionInfo()'
            Rscript -e 'installed.packages()[, c("Package", "Version")]'
            Rscript -e 'rmarkdown::pandoc_version()'
#       -  run:
      #     name: Build package
      #     command: R CMD build .
      # - run:
      #     name: Check package
      #     command: R CMD check --as-cran --no-manual *tar.gz
      - store_artifacts:
          path: ReproducibleResumeCV.Rcheck/
      - save_cache:
          key: r-pkg-cache-{{ arch }}-{{ .Branch }}
          paths:
            - "~/R/Library"
